language: java

services: 
 - docker

jobs:
  include:
    - stage: sonar_scanner
      addons:
        sonarcloud:
          organization: "olmlisa"
          token: $SONAR_SECRET
          
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=OlmLisa_sample-application-students 
