language: java

cache:
 directories: 
 - "$HOME/.m2/repository"
 - "$HOME/.sonar/cache"

services: 
 - docker

before_install: 
 - docker pull postgres:9.6 
 - docker run -d -p 5432:5432 postgres

script: 
 - mvn clean install

notifications:
 email:
   on_failure: always

deploy:
 provider: script
 script: ssh -i /tmp/travis_deploy_rsa $USER@$SERVER" sudo docker pull $IMAGE_NAME:$TAG && sudo docker rm-f app || true && sudo docker run -d --network net -p 80:8080 --name app $IMAGE_NAME:$TAG"
 on:
   branch: master
