language: java

services: 
 - docker

jobs:
  include:
    - stage: sonar_scanner
      addons:
        sonarcloud:
          organization: "olmlisa"
          token: $SONAR_SECRET
          
script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=OlmLisa_sample-application-students
    
