language: java

services: 
 - docker

jobs:
  include:
    - stage: publish_backend
      script:
        - docker build -t tp-db ./database
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker push $DOCKERHUB_USER/tp-db
    - stage: publish_httpd
      script:
        - docker build -t tp-http ./httpd
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker push $DOCKERHUB_USER/tp-http
    - stage: publish_api
      script:
        - docker build -t tp-api ./simple-api
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker push $DOCKERHUB_USER/tp-api
    - stage: sonar_scanner
      addons:
        sonarcloud:
          organization: "olmlisa"
          token: $SONAR_SECRET
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=OlmLisa_sample-application-students 
