language: java

services: 
 - docker

jobs:
  include:
    - stage: test
      script:
        - mvn clean verify
    - stage: publish_backend
      script:
        - docker build -t $DOCKERHUB_USER/tp-db ./database
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker push $DOCKERHUB_USER/tp-db
    - stage: publish_httpd
      script:
        - docker build -t $DOCKERHUB_USER/tp-http ./httpd
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker push $DOCKERHUB_USER/tp-http
    - stage: publish_api
      script:
        - docker build -t $DOCKERHUB_USER/tp-api ./simple-api
      after_success:
        - echo $DOCKERHUB_PWD | docker login --username $DOCKERHUB_USER --password-stdin
        - docker push $DOCKERHUB_USER/tp-api
    - stage: sonar_scanner
      addons:
        sonarcloud:
          organization: "olmlisa"
          token: $SONAR_SECRET
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=OlmLisa_sample-application-students 
    - stage: deploy
      addons:
        ssh_known_hosts: lisa-oulmi.takima.io
      install:
        - sudo apt update
        - sudo apt install software-properties-common
        - sudo apt-add-repository --yes --update ppa:ansible/ansible
        - sudo apt install ansible
        - ansible-galaxy install --roles-path ./roles/ geerlingguy.docker
        - ansible-galaxy install --roles-path ./roles/ weareinteractive.docker_compose
      script:
        - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out id_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
        - ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
